config/routes.rb
Rails.application.routes.draw do
 
  
 devise_for :admin_users, ActiveAdmin::Devise.config
 ActiveAdmin.routes(self) 

root 'admin/dashboard#index'

  resources :products
  resources :formulas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  
    def initialize(user)
   
           user ||= AdminUser.new # guest user (not logged in)
     
        case user.categoria # a_variable is the variable we want to compare
           when 1
             

            # can :read, ActiveAdmin::Page, :name =>"Epyg"
            # can :read, ActiveAdmin::Page, :name =>"Dashboard"
            # can :read, ActiveAdmin::Page, :name =>"grafico"
            # can :read, ActiveAdmin::Page, :name =>"Dpc"
             can [:create,:read,:update,:destroy], [Product,Formula]
             

            when 3 #adm por defecto
              can :manage, :all


        end

    end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formula.rb
class Formula < ApplicationRecord
    belongs_to :admin_user
    belongs_to :product


   
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :admin_user
    has_many :formulas
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/formulas_controller.rb
class FormulasController < InheritedResources::Base

  private

    def formula_params
      params.require(:formula).permit(:codigo)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nombre, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/grafico/_grafico.html.erb
<h3> Grafico de Cuentas Contables</h3>

<!DOCTYPE html>
<html>
    <head>
        <title>Bar char</title>

        <script
         src="https://code.jquery.com/jquery-3.1.1.min.js"
         integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
         crossorigin="anonymous"></script>
         <script src="https://code.highcharts.com/highcharts.js"></script>


            <% @vanc=400 %>


         <div id="container" style="min-width: 310px; max-width: 900px; height:<%= @vanc%>px; margin: 0 auto"></div>


    </head>

    <body>

        <script>
        $(function () {

          var myChart = Highcharts.chart('container', {
                chart: {
        type: 'bar'
    },
    title: {
        text: '<%= param20 %>'
    },
    xAxis: [{
        categories:<% nn=param1.length %>
<% conta=0 %>
 [
<%while nn>conta do%>

<%if conta==0 then%>
   "<%=param1[0] %>"
<% else %>
,"<%=param1[conta] %>"
<% end %>
<%conta=conta+1 %>
<% end %>
]
    }
  ],
    yAxis: {
        min: 2,
        title: {
            text: 'Importes en millones de soles al 31 de diciembre del 2018',
            align: 'high'
        },
        labels: {
            overflow: 'justify'
        }
    },
    legend: {
        reversed: true
    },
    tooltip: {
          valueSuffix: ' dias'
      },
    plotOptions: {
        series: {
            stacking: 'true'
        }
    },
    series: [
      {

        name: 'IMPORTES EN MONEDA NACIONAL',
        color: 'rgba(0,255,0,0.9)',
        data:  <%= param2%>
       }
  ]
})
});


        </script>

    <div id="container"></div>
    </body>
</html>

app/views/formulas/_form.html.erb
<%= form_with(model: formula, local: true) do |form| %>
  <% if formula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formula.errors.count, "error") %> prohibited this formula from being saved:</h2>

      <ul>
      <% formula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formulas/edit.html.erb
<h1>Editing Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Show', @formula %> |
<%= link_to 'Back', formulas_path %>

app/views/formulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formulas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><%= formula.codigo %></td>
        <td><%= link_to 'Show', formula %></td>
        <td><%= link_to 'Edit', edit_formula_path(formula) %></td>
        <td><%= link_to 'Destroy', formula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formula', new_formula_path %>

app/views/formulas/new.html.erb
<h1>New Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Back', formulas_path %>

app/views/formulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @formula.codigo %>
</p>

<%= link_to 'Edit', edit_formula_path(@formula) %> |
<%= link_to 'Back', formulas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nombre %></td>
        <td><%= product.descripcion %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @product.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.descripcion %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>